---
- hosts: localhost
  connection: local
  tasks:
    - name: install packages
      become: true
      dnf:
        name: [
              'https://atom.io/download/rpm',
              'kubernetes-client',
              'gnome-tweaks',
              'dconf-devel',  # gnome-terminal dracula theme
              ]
        state: present
        update_cache: true

    - include: tasks/ssh.yml
    - include: tasks/bash.yml
    - include: tasks/vim.yml
    - include: tasks/gnome.yml
#    - include: tasks/firefox.yml
#    - include: tasks/
#    - include: tasks/
