---
#- name: create /home/{{ lookup('env', 'USER') }}/bin
#  file:
#    path: "/home/{{ lookup('env', 'USER') }}/bin"
#    state: directory
#    mode: 0644

- name: download scripts
  get_url:
    url: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0755
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
  loop:
    - src: https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash
      dest: "/home/{{ lookup('env', 'USER') }}/bin/git-completion.bash"
    - src: https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh
      dest: "/home/{{ lookup('env', 'USER') }}/bin/git-prompt.sh"

- name: install dot files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0644
  loop:
    - src: files/.bash_profile
      dest: "/home/{{ lookup('env', 'USER') }}/"
    - src: files/dircolors
      dest: "/home/{{ lookup('env', 'USER') }}/.dir_colors/"

#- name:
