---
- name: run cofiguration commands
  command:
    cmd:
      - gsettings set org.gnome.desktop.wm.preferences audible-bell false
      - gsettings set org.gnome.desktop.wm.preferences visual-bell false
